name: Release on GitHub and Docker Hub

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Nix
      uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes

    - uses: cachix/cachix-action@v12
      with:
        name: airquery
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build the Docker image using Nix
      run: |
        nix build .#docker-image --out-link docker-image.tar

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and push the Docker image
      run: |
        docker load -i docker-image.tar
        export IMAGE_ID=airquery:${{github.sha}}
        export TAG_NAME=${{ github.ref_name }}
        export IMAGE_NAME=stoke/airquery:$TAG_NAME

        docker tag $IMAGE_ID $IMAGE_NAME
        docker push $IMAGE_NAME

        docker tag $IMAGE_NAME stoke/airquery:latest
        docker push stoke/airquery:latest

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
